services:
  db:
    image: postgres:latest
    container_name: sds-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sds
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sds_jwt
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - sds-network

volumes:
  pg_data:

networks:
  sds-network:
    driver: bridge